<a href="https://colab.research.google.com/github/tsuyos-u/statistical_analysis_2025/blob/master/notebooks/%E7%AC%AC01%E5%9B%9E/20250609_%E7%B5%B1%E8%A8%88%E5%88%86%E6%9E%90%E8%AB%96_Numpy_Pandas_%E5%85%A5%E9%96%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy・Pandas 入門

**このNotebookで学ぶこと**
1. Package を読み込む
1. Numpy とはなにか
  1. ndarray
  2. 算術演算
  3. インデックス参照

2. Pandas とはなにか
  1. Series
    1. Series の定義
    2. Series の選択・スライス
    3. Series のフィルタリング
    4. Series の算術
  2. DataFrame
    1. DataFrame の定義
    2. DataFrame の選択・スライス
    3. DataFrame のフィルタリング
    4. DataFrame の算術

In [3]:
# package の読み込み
import numpy as np
import pandas as pd

# 01. Numpy とはなにか (重要度 星2)
Python における行列演算ライブラリー. ほぼすべての数値演算ライブラリーがNumpyを参照している. 本講義で主に使う統計分析ライブラリーはstatsmodels, sklearnはNumpyによる行列演算を基本的に活用しています.

**おさえるべきポイント**
1. 統計分析アルゴリズムを考案するなら絶対に知っておかないこと
2. 一方，統計分析ライブリーを使う目的だけだとそこまで意識しなくて大丈夫. 存在を知っておけばオッケー．
2. PandasのDataFrameに慣れるとNumpyの存在を意識しなくなります．しかし，実際のアルゴリズムはNumpyで動いているのでPandas のDataFrameとNumpyのNDArrayの挙動の違いでバグが誘発されることがよくあります．

## 1.1 ndarray (重要度　星2)

ここでは, Numpy の基本要素である多次元配列オブジェクト，ndarrayについて紹介します

**ここで学ぶべきこと**
1. ndarray の定義
2. ndarray の形状・データ・タイプの確認方法


In [4]:
# 1次元配列
X = np.array([0, 1, 2, 3, 4])
print("X=", X)
print("Xの形状は", X.shape, end='\n\n')

# 2次元配列
Y = np.array([[0, 1, 2, 3, 4],[2, 3, 4, 5, 6]])
print("Y=", Y)
print("Yの形状は", Y.shape)
print("Yのデータタイプは", Y.dtype, end='\n\n')

# ３次元配列 (テンソル)も作れます
Z = np.array(
    [
        [[0, 1, 2, 3, 4],[2, 3, 4, 5, 6]],
        [[0, 1, 2, 3, 4],[2, 3, 4, 5, 6]]
    ]
)
print("Z=", Z)
print("Zの形状は", Z.shape)
print("Zのデータタイプは", Z.dtype)

X= [0 1 2 3 4]
Xの形状は (5,)

Y= [[0 1 2 3 4]
 [2 3 4 5 6]]
Yの形状は (2, 5)
Yのデータタイプは int64

Z= [[[0 1 2 3 4]
  [2 3 4 5 6]]

 [[0 1 2 3 4]
  [2 3 4 5 6]]]
Zの形状は (2, 2, 5)
Zのデータタイプは int64


## 1.2 ndarray の演算 (重要度 星1)

**ここで学ぶべきこと**
1. ndarrayによる4則演算
2. ndarrayによる行列演算

In [5]:
X = np.array([[0.1, 1, 2, 3], [1.1, 2, 3, 4]])
print("X=", X)
print("Xの形状は", X.shape, end="\n\n")

# 行方向への和
Y = X.sum(axis=0)
print("Y=", Y)
print("Y.shape = ", Y.shape, end="\n\n")

Y = X.sum(axis=1)
print("Y =", Y)
print("Y.shape = ", Y.shape, end="\n\n")

# 各要素に対する演算
Y = X * 10
print("X * 10 = ", Y)
Y = 1 / X
print("1 / X =", Y, end="\n\n")

# 行列と行列の積
Y = np.array([[0, 1], [2, 3], [4, 5], [6, 7]])
print("Y=", Y)
print("Y.shpae =", Y.shape)
print("X Y = ", X@Y)
print("Y X = ", Y@X, end='\n\n')

# ちょっと応用 Broacasting
Y = np.array([5, 2, 4, 3])
print("Y=", Y)
print("Y.shape=", Y.shape)
print("X=", X)
print(X * Y)

X= [[0.1 1.  2.  3. ]
 [1.1 2.  3.  4. ]]
Xの形状は (2, 4)

Y= [1.2 3.  5.  7. ]
Y.shape =  (4,)

Y = [ 6.1 10.1]
Y.shape =  (2,)

X * 10 =  [[ 1. 10. 20. 30.]
 [11. 20. 30. 40.]]
1 / X = [[10.          1.          0.5         0.33333333]
 [ 0.90909091  0.5         0.33333333  0.25      ]]

Y= [[0 1]
 [2 3]
 [4 5]
 [6 7]]
Y.shpae = (4, 2)
X Y =  [[28.  34.1]
 [40.  50.1]]
Y X =  [[ 1.1  2.   3.   4. ]
 [ 3.5  8.  13.  18. ]
 [ 5.9 14.  23.  32. ]
 [ 8.3 20.  33.  46. ]]

Y= [5 2 4 3]
Y.shape= (4,)
X= [[0.1 1.  2.  3. ]
 [1.1 2.  3.  4. ]]
[[ 0.5  2.   8.   9. ]
 [ 5.5  4.  12.  12. ]]


## 1.3 インデックス参照
ndarrayの各要素をどのように選択するのか

**ここで学ぶべきこと**
1. 要素の選択する方法
2. スライスする方法

In [6]:
# 要素の選択 (重要度 星3)
X = np.array([[0.1, 1, 2, 3], [1.1, 2, 3, 4], [2, 3, 4, 5]])
print("X=", X)
print("Xの形状は", X.shape)
print("Xの2行目, 3列目の要素は", X[1, 2], end="\n\n")

# 最後の列の要素を選択するには
print("Xの最後の列を選択するには\n", X[:, -1])
print("Xの最後から２列を選択するには\n", X[:, -2:], end="\n\n")


# スライス (重要度 星3) ファンシーインデックシング
# スライスするときは，最初に選択したインデックスは含むが最後は選択されない
print("2列目から3列目まで選択するには\n", X[:, 1:3])
print("2列目以降を選択するには\n", X[:, 1:])
print("2行目から3行目，2列目と4列目を選択するには\n", X[1:2, [1, 3]])


X= [[0.1 1.  2.  3. ]
 [1.1 2.  3.  4. ]
 [2.  3.  4.  5. ]]
Xの形状は (3, 4)
Xの2行目, 3列目の要素は 3.0

Xの最後の列を選択するには
 [3. 4. 5.]
Xの最後から２列を選択するには
 [[2. 3.]
 [3. 4.]
 [4. 5.]]

2列目から3列目まで選択するには
 [[1. 2.]
 [2. 3.]
 [3. 4.]]
2列目以降を選択するには
 [[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]]
2行目から3行目，2列目と4列目を選択するには
 [[2. 4.]]


## 2. Pandasとはなにか(重要度 星3)

本講義，終了後に自由にpandas のDataFrame を扱えるようになることが１つの目標.

**おさえるべきポイント**
1. DataFrame はこの授業で絶対に知らないと先に進めないです．データを読み込んでDataFrameを構成し，その上でデータ分析，もしくは結果をDataFrameで出力し，そこからcsvファイルを作成したりします．
2. とくに重要な演算は, 集約と集計--Groupby演算です．非常に強力なツールとなります．
3. データの読み込み・集計・結果の保存ができるようになりましょう

## 2.1 Series

ここではDataFrameに入る前にDataFrameの構成要素の１つであるSeriesについて説明します.

### 2.1.1 Series の定義 (重要度 星３)
**おさえるべきポイント**
1. Seriesの定義
2. Seriesの構成要素

In [7]:
# Series を定義する
obj = [0, 1, 2, 3, 4]
obj = pd.Series(obj)

# print でSeries を描画した場合
print("obj = ")
print(obj, end="\n\n")

# displayで Seriesを表示した場合. (HTML表現を使うことができる)
print("obj = ")
display(obj)
print("\n")

# Series は, index と numpy arrayで構成される
print("obj.index =", obj.index)
print("obj.values =", obj.values)

obj.name = "test_series"

obj = 
0    0
1    1
2    2
3    3
4    4
dtype: int64

obj = 


0    0
1    1
2    2
3    3
4    4
dtype: int64



obj.index = RangeIndex(start=0, stop=5, step=1)
obj.values = [0 1 2 3 4]


### 2.1.2 Series における要素の選択，スライス (重要度 星3)

**おさえるべきポイント**
1. Seriesの要素選択
2. Seriesにおけるインデックスのスライス

In [8]:
# Series の定義
obj2 = pd.Series(index=['a', 'c', 'd', 'e'], data=[4, 5, -7, 10], name='Series')
display(obj2)
print("\n\n")

print("obj2['a'] = ", obj2["a"])

# スライスができる．Numpyのスライスと異なり，最初のインデックス，最後のインデックスも含む点に注意が必要
print("obj2['a':'d'] = \n", obj2["a":"d"])

a     4
c     5
d    -7
e    10
Name: Series, dtype: int64




obj2['a'] =  4
obj2['a':'d'] = 
 a    4
c    5
d   -7
Name: Series, dtype: int64


### 2.1.3 Series のフィルタリング (重要度 星2)

**おさえるべきポイント**
1. フィルタリングの仕方
2. マスキング

In [9]:
obj2 = pd.Series(index=['a', 'c', 'd', 'e'], data=[4, 5, -7, 10], name='Series')

# filtering
display(obj2[obj2 >= 0])
print("\n")

# obj2 >=0 以外をnp.nan を割り当てる
display(obj2.where(obj2>=0))
print("\n")

# obj2 ==4 以外に2 を割り当てる
display(obj2.where(obj2==4, 2))
print("\n")

# obj2 >= 0 にnp.nanを割り当てる
display(obj2.mask(obj2>=0))
print("\n")

# obj2 == 5 に7を割り当てる
display(obj2.mask(obj2>=0, 7))

a     4
c     5
e    10
Name: Series, dtype: int64

a     4.0
c     5.0
d     NaN
e    10.0
Name: Series, dtype: float64

a    4
c    2
d    2
e    2
Name: Series, dtype: int64

a    NaN
c    NaN
d   -7.0
e    NaN
Name: Series, dtype: float64

a    7
c    7
d   -7
e    7
Name: Series, dtype: int64

### 2.1.4 Series における算術 (重要度 星3)

**おさえるべきポイント**
1. Seriesにおける算術
2. Seriesの算術
2. NULL値があるときのSeriesの算術

In [10]:
# obj2 を２倍
display(obj2 * 2)
print("\n")

# obj2の足し算
print(obj2.sum(), end='\n\n')

# obj2の平均
print(obj2.mean(), end='\n\n')

# obj2の中央値
print(obj2.median(), end='\n\n')

# obj2の25percentile
print(obj2.quantile(0.25), end='\n\n')

# obj2の75percentile
print(obj2.quantile(0.75), end='\n\n')

# 統計量の描画
display(obj2.describe())
print("\n\n\n")

# obj3[['a', 'c']]

a     8
c    10
d   -14
e    20
Name: Series, dtype: int64



12

3.0

4.5

1.25

6.25



count     4.000000
mean      3.000000
std       7.164728
min      -7.000000
25%       1.250000
50%       4.500000
75%       6.250000
max      10.000000
Name: Series, dtype: float64

In [11]:
# obj3 < 0 をnan(NULL値)でマスキング
obj3 = obj2.mask(obj2<0, np.nan)
display(obj3)

# Null は無視する
print("counts = ", obj3.count(), end="\n\n")
print("sum = ", obj3.sum(), end="\n\n")
print("mean = ", obj3.mean(), end="\n\n")
print("median = ", obj3.median(), end="\n\n")

# 注意点 numpy array だとnull値があるとnanが返ってくる (重要度 星３)
print("ndarray =", obj3.values.sum())

# Null値をfillする
obj3.fillna(0)

a     4.0
c     5.0
d     NaN
e    10.0
Name: Series, dtype: float64

counts =  3

sum =  19.0

mean =  6.333333333333333

median =  5.0

ndarray = nan


a     4.0
c     5.0
d     0.0
e    10.0
Name: Series, dtype: float64

In [12]:
# DataFrame
# DataFrame は Seriesを集めて表形式にしたもの (table データ)

## 2 DataFrame

ここでは，本講義の主役であるDataFrameについて説明します.
DataFrame はSeriesを集めて表形式にしたもの (tableデータ)

## 2.1 DataFrame の定義

**おさえるべきポイント**
1. データフレームの定義
2. データフレームの中身の確認方法

In [13]:
# データフレームの定義
data = {}
data['prefecture'] = ["Osaka", "Osaka", "Osaka", "Nara", "Nara", "Nara"]
data['year'] = [2000, 2001, 2002, 2001, 2002, 2003]
data['pop'] = [880.51, 880.51, 879.35, 142.9, 127.39, 127.87]
df = pd.DataFrame(data)

# 別の方法としては，dictでSeriesをつなげる
data = {}
data['prefecture'] = pd.Series(
  ["Osaka", "Osaka", "Osaka", "Nara", "Nara", "Nara"]
)

data['year'] = pd.Series([2000, 2001, 2002, 2001, 2002, 2003])
data['pop'] = pd.Series([880.51, 880.51, 879.35, 142.9, 127.39, 127.87])
df = pd.DataFrame(data)

# 先頭を確認する (defaultは5行)
display(df.head())

# 末尾を確認する (defaultは5行)
display(df.tail())

prefecture  year     pop
0      Osaka  2000  880.51
1      Osaka  2001  880.51
2      Osaka  2002  879.35
3       Nara  2001  142.90
4       Nara  2002  127.39

prefecture  year     pop
1      Osaka  2001  880.51
2      Osaka  2002  879.35
3       Nara  2001  142.90
4       Nara  2002  127.39
5       Nara  2003  127.87

## 2.2 DataFrame の要素の選択・スライシング (重要度　星3)

**おさえるべきポイント**
1. データフレームの要素の選択 (重要度　星３)
  1. columns の選択
  1. rows の選択  
2. データフレームのスライス
  1. columns のスライス
  2. rows のスライス

In [14]:
# columns の選択

display(df['prefecture'])
print("df['prefecture']の型は", type(df['prefecture']), end="\n\n")

# 次のようにリストにするとデータフレームになる点に注意
display(df[['prefecture']])
print("df['prefecture']の型は", type(df[['prefecture']]), end='\n\n')

# columns の複数要素の選択
display("'prefecture', 'pop'を選択", df[['prefecture', 'pop']])

# 行を選択するには
print("2行目を選択するには\n", df.loc[1], end='\n\n')

# 行と列を同時に指定するには
print("2行目のpopを指定する", df.loc[1, 'pop'], end='\n\n')

# 複数の行を選択するには
display(df.loc[[1, 3, 5], :])
print("\n\n")

# 複数の行，列を選択するには
display(df.loc[[1, 3], ['prefecture', 'pop']])
print("\n\n")

# 1 〜 3 を選択する スライス. ここで，最後のインデックスである3を含んでいることに注意
display(df.loc[1:3])

# year から pop まで
display(df.loc[1:3, 'year':'pop'])

0    Osaka
1    Osaka
2    Osaka
3     Nara
4     Nara
5     Nara
Name: prefecture, dtype: object

df['prefecture']の型は <class 'pandas.core.series.Series'>



prefecture
0      Osaka
1      Osaka
2      Osaka
3       Nara
4       Nara
5       Nara

df['prefecture']の型は <class 'pandas.core.frame.DataFrame'>



"'prefecture', 'pop'を選択"

prefecture     pop
0      Osaka  880.51
1      Osaka  880.51
2      Osaka  879.35
3       Nara  142.90
4       Nara  127.39
5       Nara  127.87

2行目を選択するには
 prefecture     Osaka
year            2001
pop           880.51
Name: 1, dtype: object

2行目のpopを指定する 880.51



prefecture  year     pop
1      Osaka  2001  880.51
3       Nara  2001  142.90
5       Nara  2003  127.87

prefecture     pop
1      Osaka  880.51
3       Nara  142.90

prefecture  year     pop
1      Osaka  2001  880.51
2      Osaka  2002  879.35
3       Nara  2001  142.90

year     pop
1  2001  880.51
2  2002  879.35
3  2001  142.90

In [15]:
# 一列追加する
df.loc[:, 'debt'] = np.nan
# df = df.assign(debt=np.nan)
display(df)

df.loc[:, 'debt'] = 1e3
display(df)

# 一行追加する
df.loc[6] = pd.Series({'prefecture': "Hygo", 'year': 2003, "pop": 560.20})
display(df)

prefecture  year     pop  debt
0      Osaka  2000  880.51   NaN
1      Osaka  2001  880.51   NaN
2      Osaka  2002  879.35   NaN
3       Nara  2001  142.90   NaN
4       Nara  2002  127.39   NaN
5       Nara  2003  127.87   NaN

prefecture  year     pop    debt
0      Osaka  2000  880.51  1000.0
1      Osaka  2001  880.51  1000.0
2      Osaka  2002  879.35  1000.0
3       Nara  2001  142.90  1000.0
4       Nara  2002  127.39  1000.0
5       Nara  2003  127.87  1000.0

prefecture  year     pop    debt
0      Osaka  2000  880.51  1000.0
1      Osaka  2001  880.51  1000.0
2      Osaka  2002  879.35  1000.0
3       Nara  2001  142.90  1000.0
4       Nara  2002  127.39  1000.0
5       Nara  2003  127.87  1000.0
6       Hygo  2003  560.20     NaN

In [16]:
df = pd.DataFrame(data)
# index をset する
df2 = df.set_index('prefecture')
display(df2)

# index をreset する
display(df2.reset_index())

# indexを複数指定する
display(df.set_index(['prefecture', 'year']))

# index で指定するのではなく，何行，何列で指定する
display(df2.iloc[0, 1])

# iloc によるスライス (4行目が含まれていないことに注意)
display(df2.iloc[0:3])

# numpy array を取得する．index, columnsを含まない行列が取得できる
display(df.values)
display(df2.values)

# reindex
display(df.reindex(index=[0, 1, 4, 5, 10]))
display(df.reindex(columns=['year', 'pop', 'area']))

# index のset_index
display(df.set_index('prefecture'))

# reset_index
# df = pd.DataFrame(data)
display(df.reset_index())
df2 = df2.reset_index()
display(df2)

# rename index
df2 = df2.rename(columns={'index': 'prefecture'})

# set_index
df2 = df2.set_index('prefecture')
display(df2)


year     pop
prefecture              
Osaka       2000  880.51
Osaka       2001  880.51
Osaka       2002  879.35
Nara        2001  142.90
Nara        2002  127.39
Nara        2003  127.87

prefecture  year     pop
0      Osaka  2000  880.51
1      Osaka  2001  880.51
2      Osaka  2002  879.35
3       Nara  2001  142.90
4       Nara  2002  127.39
5       Nara  2003  127.87

pop
prefecture year        
Osaka      2000  880.51
           2001  880.51
           2002  879.35
Nara       2001  142.90
           2002  127.39
           2003  127.87

np.float64(880.51)

year     pop
prefecture              
Osaka       2000  880.51
Osaka       2001  880.51
Osaka       2002  879.35

array([['Osaka', 2000, 880.51],
       ['Osaka', 2001, 880.51],
       ['Osaka', 2002, 879.35],
       ['Nara', 2001, 142.9],
       ['Nara', 2002, 127.39],
       ['Nara', 2003, 127.87]], dtype=object)

array([[2000.  ,  880.51],
       [2001.  ,  880.51],
       [2002.  ,  879.35],
       [2001.  ,  142.9 ],
       [2002.  ,  127.39],
       [2003.  ,  127.87]])

prefecture    year     pop
0       Osaka  2000.0  880.51
1       Osaka  2001.0  880.51
4        Nara  2002.0  127.39
5        Nara  2003.0  127.87
10        NaN     NaN     NaN

year     pop  area
0  2000  880.51   NaN
1  2001  880.51   NaN
2  2002  879.35   NaN
3  2001  142.90   NaN
4  2002  127.39   NaN
5  2003  127.87   NaN

year     pop
prefecture              
Osaka       2000  880.51
Osaka       2001  880.51
Osaka       2002  879.35
Nara        2001  142.90
Nara        2002  127.39
Nara        2003  127.87

index prefecture  year     pop
0      0      Osaka  2000  880.51
1      1      Osaka  2001  880.51
2      2      Osaka  2002  879.35
3      3       Nara  2001  142.90
4      4       Nara  2002  127.39
5      5       Nara  2003  127.87

prefecture  year     pop
0      Osaka  2000  880.51
1      Osaka  2001  880.51
2      Osaka  2002  879.35
3       Nara  2001  142.90
4       Nara  2002  127.39
5       Nara  2003  127.87

year     pop
prefecture              
Osaka       2000  880.51
Osaka       2001  880.51
Osaka       2002  879.35
Nara        2001  142.90
Nara        2002  127.39
Nara        2003  127.87

## 2.3 DataFrame のフィルタリング (重要度　星3)

**おさえるべきポイント**
1. データフレームの条件に基づくフィルタリング
2. データフレームのマスクキング

  

In [17]:
df = pd.DataFrame(
    np.arange(16).reshape((4, 4)),
    index=['Osaka', 'Nara', 'Tokyo', 'Fukuoka'],
    columns=['one', 'two','three', 'four']
)

# 5以下のdataframeだけ表示する
df[df < 5]
display(df)

one  two  three  four
Osaka      0    1      2     3
Nara       4    5      6     7
Tokyo      8    9     10    11
Fukuoka   12   13     14    15

one   two  three  four
Osaka     NaN   NaN    NaN   NaN
Nara      NaN   5.0    6.0   7.0
Tokyo     8.0   9.0   10.0  11.0
Fukuoka  12.0  13.0   14.0  15.0

one  two  three  four
Osaka    0.0  1.0    2.0   3.0
Nara     4.0  NaN    NaN   NaN
Tokyo    NaN  NaN    NaN   NaN
Fukuoka  NaN  NaN    NaN   NaN

In [19]:
# 5以下をマスクする
display(df.mask(df < 5))

# 5以下を除く部分をマスクする
display(df.where(df < 5))

one   two  three  four
Osaka     NaN   NaN    NaN   NaN
Nara      NaN   5.0    6.0   7.0
Tokyo     8.0   9.0   10.0  11.0
Fukuoka  12.0  13.0   14.0  15.0

one  two  three  four
Osaka    0.0  1.0    2.0   3.0
Nara     4.0  NaN    NaN   NaN
Tokyo    NaN  NaN    NaN   NaN
Fukuoka  NaN  NaN    NaN   NaN

In [18]:
# 算術
display(df.sum().sum())
display(df.sum(axis=1))
display(df.sum(axis=0))

# 平均
display(df.mean())
display(df.mean(axis=0))
display(df.mean(axis=1))

# print(df.std(axis=1))
# print(df.std(axis=0))
print(df.describe())
print(df.count(axis=1))

# ブロードキャスト
df - df.sum()

df - df.sum(axis=1)

display(df.shape)

# .Tは転置で行と列を入れ替える
display((df.T - df.sum(axis=1)).T)

np.int64(120)

Osaka       6
Nara       22
Tokyo      38
Fukuoka    54
dtype: int64

one      24
two      28
three    32
four     36
dtype: int64

one      6.0
two      7.0
three    8.0
four     9.0
dtype: float64

one      6.0
two      7.0
three    8.0
four     9.0
dtype: float64

Osaka       1.5
Nara        5.5
Tokyo       9.5
Fukuoka    13.5
dtype: float64

             one        two      three       four
count   4.000000   4.000000   4.000000   4.000000
mean    6.000000   7.000000   8.000000   9.000000
std     5.163978   5.163978   5.163978   5.163978
min     0.000000   1.000000   2.000000   3.000000
25%     3.000000   4.000000   5.000000   6.000000
50%     6.000000   7.000000   8.000000   9.000000
75%     9.000000  10.000000  11.000000  12.000000
max    12.000000  13.000000  14.000000  15.000000
Osaka      4
Nara       4
Tokyo      4
Fukuoka    4
dtype: int64


(4, 4)

one  two  three  four
Osaka     -6   -5     -4    -3
Nara     -18  -17    -16   -15
Tokyo    -30  -29    -28   -27
Fukuoka  -42  -41    -40   -39